### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by A3148475824** [Zebeqo/Bangumi#144]
[登陆不上啊[]()
![Screenshot_20230213-025731](https://user-images.githubusercontent.com/70214970/218331297-6142a8a0-26fc-47b2-80b4-41cb4597e14f.png)

**Comment by Zebeqo** [comment]
确实。我看看问题，感谢反馈！

**Comment by Zebeqo** [comment]
现在应该可以了。换域名的时候忘记在 Production 里改 `NEXTAUTH_URL` 环境变量了。非常感谢反馈！
