### ISSUE TITLE
fix: should logout when the token expires

### ISSUE THREAD

**Issue by A3148475824** [Zebeqo/Bangumi#154]
问题详情
{
  "title": "Unauthorized",
  "details": {
    "path": "/v0/users/673172/collections",
    "method": "GET"
  },
  "description": "access token has been expired or doesn't exist"
}

**Comment by Zebeqo** [comment]
这个需要你重新登录一下，之前身份验证过期了。

我这两天完善一下认证，过期的时候自动退出登录。

感谢反馈！

**Comment by A3148475824** [comment]
好的谢谢



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 2, 2023 22:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Zebeqo/Bangumi] bug (Issue #154)




 
这个需要你重新登录一下，之前身份验证过期了。
 
我这两天完善一下认证，过期的时候自动退出登录。
 
感谢反馈！
